import { Component } from '@angular/core';

@Component({
  selector: 'mab-card-demos',
  templateUrl: './card-demos.component.html',
  styleUrls: ['./card-demos.component.scss'],
})
export class CardDemosComponent {
  displayedColumns = [
    'id',
    'firstName',
    'lastName',
    'email',
    'hoursWorked',
    'hourlyWage',
  ];
  tabularContent = [
    {
      id: 1,
      firstName: 'Henry',
      lastName: 'Holmes',
      email: 'hholmes0@goodreads.com',
      hoursWorked: 29,
      hourlyWage: 19,
    },
    {
      id: 2,
      firstName: 'Harold',
      lastName: 'Cox',
      email: 'hcox1@who.int',
      hoursWorked: 18,
      hourlyWage: 11,
    },
    {
      id: 3,
      firstName: 'Brian',
      lastName: 'Garcia',
      email: 'bgarcia2@addthis.com',
      hoursWorked: 4,
      hourlyWage: 17,
    },
    {
      id: 4,
      firstName: 'Patricia',
      lastName: 'Young',
      email: 'pyoung3@wix.com',
      hoursWorked: 47,
      hourlyWage: 12,
    },
    {
      id: 5,
      firstName: 'Jose',
      lastName: 'Jacobs',
      email: 'jjacobs4@prweb.com',
      hoursWorked: 45,
      hourlyWage: 12,
    },
    {
      id: 6,
      firstName: 'Rachel',
      lastName: 'Carter',
      email: 'rcarter5@t.co',
      hoursWorked: 34,
      hourlyWage: 17,
    },
    {
      id: 7,
      firstName: 'Ashley',
      lastName: 'Reyes',
      email: 'areyes6@bing.com',
      hoursWorked: 60,
      hourlyWage: 9,
    },
    {
      id: 8,
      firstName: 'Antonio',
      lastName: 'Cruz',
      email: 'acruz7@jigsy.com',
      hoursWorked: 38,
      hourlyWage: 10,
    },
    {
      id: 9,
      firstName: 'Randy',
      lastName: 'Cook',
      email: 'rcook8@state.tx.us',
      hoursWorked: 22,
      hourlyWage: 15,
    },
    {
      id: 10,
      firstName: 'Phillip',
      lastName: 'Long',
      email: 'plong9@un.org',
      hoursWorked: 39,
      hourlyWage: 19,
    },
    {
      id: 11,
      firstName: 'Andrea',
      lastName: 'Simpson',
      email: 'asimpsona@is.gd',
      hoursWorked: 4,
      hourlyWage: 10,
    },
    {
      id: 12,
      firstName: 'Tina',
      lastName: 'Rice',
      email: 'triceb@wisc.edu',
      hoursWorked: 18,
      hourlyWage: 20,
    },
    {
      id: 13,
      firstName: 'Larry',
      lastName: 'Foster',
      email: 'lfosterc@wikia.com',
      hoursWorked: 26,
      hourlyWage: 19,
    },
    {
      id: 14,
      firstName: 'Philip',
      lastName: 'Hall',
      email: 'phalld@vkontakte.ru',
      hoursWorked: 32,
      hourlyWage: 10,
    },
    {
      id: 15,
      firstName: 'Annie',
      lastName: 'Gilbert',
      email: 'agilberte@ucsd.edu',
      hoursWorked: 57,
      hourlyWage: 20,
    },
    {
      id: 16,
      firstName: 'Wanda',
      lastName: 'Myers',
      email: 'wmyersf@gravatar.com',
      hoursWorked: 14,
      hourlyWage: 12,
    },
    {
      id: 17,
      firstName: 'Robert',
      lastName: 'Palmer',
      email: 'rpalmerg@usnews.com',
      hoursWorked: 30,
      hourlyWage: 12,
    },
    {
      id: 18,
      firstName: 'Judith',
      lastName: 'King',
      email: 'jkingh@auda.org.au',
      hoursWorked: 39,
      hourlyWage: 14,
    },
    {
      id: 19,
      firstName: 'Sarah',
      lastName: 'Mendoza',
      email: 'smendozai@fc2.com',
      hoursWorked: 16,
      hourlyWage: 20,
    },
    {
      id: 20,
      firstName: 'Marilyn',
      lastName: 'Watson',
      email: 'mwatsonj@google.com.hk',
      hoursWorked: 19,
      hourlyWage: 19,
    },
  ];
}
